### ISSUE TITLE
Use 0x API to fetch the orders

### ISSUE THREAD

**Issue by talegift** [build-finance/metric-frontend#13]
Design: https://www.figma.com/file/E2j6e6tcbjmraEjhupg32a/Metric?node-id=197%3A19

Use 0x API to display orders of the selected token pair https://0x.org/docs/api#get-srav3orderbook

This task is only to fetch and display the orderbook. Order creation and filling will be a part of another task.

Also please notice the top navigation switcher (Quick swap / Limit orders). Which is a part of this task.

**Comment by SHA-2048** [comment]
FYI, I'm starting to work on this one.

**Comment by SHA-2048** [comment]
@talegift and @vfatouros: Just to understand what is needed here. 

As I understand it the order book is the list of asks/bids ordered by price. What is not clear to me is, do one line corresponds to 1 order or does it represent the sum of orders with the same price ?

**Comment by talegift** [comment]
It should be a sum of orders with the same/similar price. Grouping should be done to 3 decimal points.

For example, 3 orders, each with 1.1111 - 1 dai, 1.1112 - 1 dai, 1.1113 - 2 dai should be grouped as one line showing as price: 1.111, amount: 4 dai.

Let's limit the number of lines to 50 for now. 25 bids, 25 asks. And make it scrollable.

Similar to how https://oasis.app/trade/market/WETH/DAI works

**Comment by SHA-2048** [comment]
Posting progress status. I can query 0x API and display the order book with fixed couple of tokens.


What is left to be done:
- Finalize the layout to have the orderbook scrollable.
- Make order book change whenever selected couple of token has changed.

One point is not clear to me. 
- Do we need to refresh the order book once displayed? if yes, which frequency is best ?

**Comment by talegift** [comment]
Can we add a check and remove the top nav "swap / limit" if the URL contains "metric.exchange"

Since the feature is not finished yet.
