### ISSUE TITLE
Weird Select Token behavior

### ISSUE THREAD

**Issue by lepidotteri** [build-finance/metric-frontend#20]
Maybe this is being worked on, but I noticed that wen clicking the "SELECT TOKEN" input, instead of spawning the dialog window, it just deplicates the swap estimates box below

![qqqqqqqqqqqqqqqqqqqqqqqqqqqqqq](https://user-images.githubusercontent.com/45174270/95827915-a0131e00-0d34-11eb-9004-ee9e03f218d3.JPG)

**Comment by talegift** [comment]
I think we should do this one first before anything else. This makes a very bad impression on anyone using the site.

**Comment by SHA-2048** [comment]
OK will check it !
