### ISSUE TITLE
0x order filling

### ISSUE THREAD

**Issue by talegift** [build-finance/metric-frontend#31]
When the user enters input & output amounts and tokens which should be matched to existing orders, the order should not be posted but rather filled.

For example, given the order book:
- 1 ETH for 400 DAI
- 1.5 ETH for 403 DAI

And user entering an order of 405 DAI for 1 ETH, the user should fill the order "1 ETH for 400" since that price is better than what he has selected.

If the user selects a large order amount (2 ETH in this case) and the order book has enough orders to fill his full order, he should fill multiple orders. So he would fill "1 ETH for 400 DAI" fully and "1.5 ETH for 403 DAI" only for 0.5 ETH.

If there is not enough liquidity, he should fill only available orders and post the remaining amount as a new order into the order book.

**Comment by SHA-2048** [comment]
This looks like an implementation of an order with a market price right ? So not strictly a `limit order`. Do we need to change the interface to make it clear for the user that it behaves that way ?

**Comment by SHA-2048** [comment]
@talegift I've pushed my dev into a new branch for this.

I'm stuck on this error when submitting the fillOrder query for now:

`gas required exceeds allowance (12512158) or always failing transaction `

tried to ask for some help in the 0x discrod, will see ....

**Comment by SHA-2048** [comment]
Now I managed to make it work with metamask. apparently the 0x js api was validating the transaction and rejecting it due to too high gas cost. The gas is still high but we can now actually see it in metamask window:

![image](https://user-images.githubusercontent.com/8516712/97104889-83bd9c80-16b7-11eb-9db2-ac9347b40235.png)

**Comment by talegift** [comment]
It's definitely a limit order.

Market = use full input amount to buy **any output amount at any price**
Limit = use a portion or whole input amount to buy output amount at the price specified or better.

Normal exchange is doing the order matching in the backend.
With 0x, it's a responsibility of the client to do the order matching.
