### ISSUE TITLE
Introduce output token selector

### ISSUE THREAD

**Issue by talegift** [build-finance/metric-frontend#54]
Having been thinking about specific places Metric could be used, it seems necessary to have the ability to select both input and output tokens.

For example, this would allow us to:
- Buy BUILD directly with ETH without the buyer needing to first sell their ETH
- Sell CPOOL directly to ESD and vice-versa (http://esd.money/)

UI should look like this: https://share.getcloudapp.com/L1uQ1mQQ

This PR should also support market URLs: http://metric.exchange/#/input_token/output_token

**Comment by SHA-2048** [comment]
We cannot make orders with ETH on 0x, it only supports WETH
The 10 DAI limit will be difficult to enforce if we open all possible pairs. I'll do a first implementation without the limit on orders that do no involve DAI. Then we'll look into how to generalize the limit to all tokens.
