### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by eyooooo** [build-finance/metric-frontend#82]
after cloning the project, `npm install` fails

```
root@farmdev:/opt/metric-frontend-master# npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: metric-frontend@1.0.0
npm ERR! Found: riot@5.0.0
npm ERR! node_modules/riot
npm ERR!   riot@"^5.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer riot@"^4.11.1" from @riotjs/hot-reload@4.0.1
npm ERR! node_modules/@riotjs/hot-reload
npm ERR!   dev @riotjs/hot-reload@"^4.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-18T18_28_48_973Z-debug.log
```

**Comment by SHA-2048** [comment]
I cleaned my cache and all installed dependencies and npm install works for me still. Here is my setup:

`node: v10.9.0`
`npm: 6.2.0`
`OS: Windows 10`

Also works for other project contributors as no one reported the issue

@eyooooo what versions of node/npm you have ?

**Comment by eyooooo** [comment]
Thanks @SHA-2048 my setup is:

node: v15.0.1
npm: 7.0.3
OS: Ubuntu 18.04.5 LTS

**Comment by eyooooo** [comment]
Yall arent running your prod web server on Win10 are you? :|

**Comment by eyooooo** [comment]
Looks like downgrading to node 14 fixed this.

**Comment by SHA-2048** [comment]
> Yall arent running your prod web server on Win10 are you? :|

No, it's just my dev setup that is this way. It's not by choice I have to say.
